controllers:
    resource: ../../src/Controller/
    type: annotation

api_controllers:
    resource: ../../src/Controller/Api/
    type: annotation
    defaults: { _format: 'json' }
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
